# Generated by Django 3.1.5 on 2021-01-21 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jop_type',
            field=models.CharField(choices=[('computer since', 'computer since'), ('artificial intelligence', 'artificial intelligence'), ('CC', 'CC')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
