# Generated by Django 3.1.5 on 2021-01-21 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20210122_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
